In [1]:
import numpy as np
import torch

In [6]:
# 和numpy比较常量
np_data = np.arange(6).reshape(2, 3)
torch_data = torch.from_numpy(np_data)
torch2array = torch_data.numpy()

print("np_data:\n", np_data, "\ntorch_data:\n", torch_data, "\ntorch2array:\n", torch2array)

np_data:
 [[0 1 2]
 [3 4 5]] 
torch_data:
 tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
torch2array:
 [[0 1 2]
 [3 4 5]]


In [7]:
# abs 绝对值计算
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)  # 转换成32位浮点 tensor
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),          # [1 2 1 2]
    '\ntorch: ', torch.abs(tensor)      # [1 2 1 2]
)

# sin   三角函数 sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: ', torch.sin(tensor)  # [-0.8415 -0.9093  0.8415  0.9093]
)

# mean  均值
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),         # 0.0
    '\ntorch: ', torch.mean(tensor)     # 0.0
)


abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])

sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])

mean 
numpy:  0.0 
torch:  tensor(0.)


In [10]:
# matrix multiplication 矩阵点乘
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 转换成32位浮点 tensor
# correct method
print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy\n: ', np.matmul(data, data),     # [[7, 10], [15, 22]]
    '\ntorch\n: ', torch.mm(tensor, tensor)   # [[7, 10], [15, 22]]
)


matrix multiplication (matmul) 
numpy
:  [[ 7 10]
 [15 22]] 
torch
:  tensor([[ 7., 10.],
        [15., 22.]])


In [14]:
# pytorch变量表示
from torch.autograd import Variable

tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad=True)

t_out = torch.mean(tensor * tensor)
v_out = torch.mean(variable * variable)

print(t_out)
print(v_out)

v_out.backward()
print(variable.grad) # 对v_out求 梯度也会影响到variable

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
