In [1]:
import torch

In [2]:
import numpy as np

### torch 基本处理单元

In [3]:
# 返回的数组大小5x4的矩阵
torch.Tensor(5, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
# 返回的数组大小是5x4的矩阵，初始化是0~1的均匀分布
torch.rand(5, 4)

tensor([[0.9395, 0.2675, 0.4903, 0.2578],
        [0.8377, 0.7548, 0.5897, 0.9951],
        [0.3166, 0.7359, 0.1234, 0.2832],
        [0.8168, 0.7111, 0.3904, 0.6255],
        [0.1712, 0.3807, 0.3037, 0.5572]])

In [5]:
# 得到矩阵大小
a = torch.rand(5, 4)
a.size()

torch.Size([5, 4])

In [6]:
# numpy 类似的返回5x4大小的矩阵
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# numpy 和 torch.Tensor 之间的转换
# from Tensor to Numpy
a = torch.rand(5, 4)
b = a.numpy()
print(b)

[[0.57740414 0.53184724 0.41207242 0.14435506]
 [0.99191034 0.6020316  0.5345968  0.7392254 ]
 [0.92170674 0.09100401 0.629193   0.18233329]
 [0.46986914 0.04344964 0.6349571  0.32299036]
 [0.9720333  0.5746105  0.90167856 0.28943193]]


In [8]:
# from Numpy to Tensor
a = np.array([[3, 4], [3, 6]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 4],
        [3, 6]], dtype=torch.int32)


运算和numpy类似

In [9]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3

In [10]:
print(c * x)

tensor([[2.0844, 2.0193, 0.1426, 0.9634],
        [2.0588, 0.8789, 1.2974, 2.7011],
        [0.8467, 2.9199, 0.9122, 0.3748],
        [2.0518, 2.6167, 1.8637, 0.5765],
        [1.7241, 2.7067, 0.2687, 0.4826]])


In [11]:
print(x + y)

tensor([[1.1383, 0.8924, 0.2364, 1.2413],
        [1.2620, 0.8822, 0.4890, 1.6868],
        [1.1702, 1.6065, 0.4789, 0.2381],
        [1.3399, 1.1426, 1.2302, 1.1450],
        [1.2268, 1.2695, 0.8977, 0.7646]])


In [12]:
print(x.add(y))

tensor([[1.1383, 0.8924, 0.2364, 1.2413],
        [1.2620, 0.8822, 0.4890, 1.6868],
        [1.1702, 1.6065, 0.4789, 0.2381],
        [1.3399, 1.1426, 1.2302, 1.1450],
        [1.2268, 1.2695, 0.8977, 0.7646]])


In [13]:
# 可以直接进行操作改变原对象，x+y或者x.add()并不会改变x，但是x.add_()则会对x进行改变
x.add_(y)

tensor([[1.1383, 0.8924, 0.2364, 1.2413],
        [1.2620, 0.8822, 0.4890, 1.6868],
        [1.1702, 1.6065, 0.4789, 0.2381],
        [1.3399, 1.1426, 1.2302, 1.1450],
        [1.2268, 1.2695, 0.8977, 0.7646]])

In [14]:
print(x)

tensor([[1.1383, 0.8924, 0.2364, 1.2413],
        [1.2620, 0.8822, 0.4890, 1.6868],
        [1.1702, 1.6065, 0.4789, 0.2381],
        [1.3399, 1.1426, 1.2302, 1.1450],
        [1.2268, 1.2695, 0.8977, 0.7646]])


将 torch.Tensor 放到 GPU 上

In [3]:
# 判断一下电脑是否支持GPU
torch.cuda.is_available()

True

In [4]:
a = torch.rand(5, 4)
a = a.cuda()
print(a)

tensor([[0.5052, 0.0086, 0.2634, 0.1298],
        [0.0589, 0.8489, 0.0683, 0.4833],
        [0.3443, 0.4708, 0.1769, 0.1613],
        [0.9588, 0.9737, 0.1310, 0.2063],
        [0.7629, 0.4277, 0.5019, 0.6811]], device='cuda:0')


### torch 的自动求导功能
torch 和大部分框架一样有着自动求导功能，对象不再是 torch.Tensor，而是torch.autograd.Variable

本质上Variable和Tensor没有什么区别，不过Variable会放在一个计算图里面，可以进行前向传播和反向传播以及求导  

![1.png](http://upload-images.jianshu.io/upload_images/3623720-1c2694b72e0341ce.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

里面的creator表示通过什么操作得到的这个Variable，grad表示反向传播的梯度

In [18]:
from torch.autograd import Variable

In [19]:
# requires_grad 表示是否对其求梯度，默认是False
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4
z

tensor([15.], grad_fn=<AddBackward0>)

In [20]:
# 对 x 和 y 分别求导
z.backward()

In [21]:
# x 的导数和 y 的导数
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([2.])
dz/dy: tensor([1.])


In [31]:
# 对矩阵的求导
x = torch.rand([2,3])
x = Variable(x, requires_grad = True)

y = x * 2
print(y)
y.backward(torch.FloatTensor([[0.5, 0.25, 0.125],[1, 1, 1]]))
print(x.grad.data)

tensor([[0.7913, 1.7630, 0.0804],
        [0.4106, 1.3172, 0.4514]], grad_fn=<MulBackward0>)
tensor([[1.0000, 0.5000, 0.2500],
        [2.0000, 2.0000, 2.0000]])


### 神经网络部分

所依赖的主要是 torch.nn 和 torch.nn.functional

torch.nn 里面有着所有的神经网络的层的操作，其用来构建网络，只有执行一次网络的运算才执行一次

torch.nn.functional 表示的是直接对其做一次向前运算操作

In [ ]:
from torch import nn
import torch.nn.functional as F

In [ ]:
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10, 3)
        # 具体每种层的参数可以去查看文档
        
    def forward(self, x):
        # 定义向前传播
        out = self.conv1(x)
        return out