In [5]:
# np.unique(arr)
# 该函数是去除数组arr中的重复数字，并进行排序之后输出。
import numpy as np
arr = np.array([1,2,3,4,5,1,3,5])
for i in np.unique(arr):
    print(i)
print(np.unique(arr))

1
2
3
4
5
[1 2 3 4 5]


In [7]:
# np.where(condition,x,y)
# 满足条件数组变为x（对应的值），否则为y（对应的值）
z = [True,False,True,False,True]
x = np.random.randn(5)
print(x)
y = np.random.randn(5)
print(y)
re = np.where(z,x,y)
print(re)

[ 0.22018542 -0.63293371 -2.01900053 -0.5990022   2.92162206]
[ 1.18354533  2.05011748 -1.53362536 -0.66313988  0.88346702]
[ 0.22018542  2.05011748 -2.01900053 -0.66313988  2.92162206]
